# Generated by Django 4.1.2 on 2022-10-26 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0002_follower_isaccepted_alter_author_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='inbox', editable=False, max_length=5)),
                ('dataType', models.CharField(choices=[('post', 'post'), ('follow', 'follow'), ('like', 'like'), ('comment', 'comment')], max_length=7)),
                ('data', models.JSONField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
    ]
