# Generated by Django 4.1.2 on 2022-10-26 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_follower_isaccepted_alter_author_host_and_more'),
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inboxes', to='authors.author'),
        ),
    ]
