# Generated by Django 4.1.2 on 2022-10-27 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_follower_isaccepted_alter_author_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profileImage',
            field=models.URLField(default='https://i.imgur.com/k7XVwpB.jpeg'),
        ),
    ]
