# Generated by Django 4.1.2 on 2022-10-20 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('type', models.CharField(default='author', max_length=255)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('host', models.URLField()),
                ('displayName', models.CharField(max_length=255)),
                ('github', models.URLField()),
                ('profileImage', models.URLField()),
                ('isAuthorized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_authors', to='authors.author')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_followers', to='authors.author')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='followers',
            field=models.ManyToManyField(through='authors.Follower', to='authors.author'),
        ),
    ]
