# Generated by Django 4.1.2 on 2022-10-22 18:24

import authors.models
from django.db import migrations, models
import utils.model_utils


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(default=authors.models.get_scheme_and_netloc, editable=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(default=utils.model_utils.generate_random_string, editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(default='author', editable=False, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('author', 'follower')},
        ),
    ]
